import assert from 'node:assert/strict';
import { ArenaEngine, WEAPONS, blocked, validInput } from '../src/arena-engine.js';

const idle = { x: 0, y: 0, angle: 0, fire: false, reload: false, trigger: 0 };
function arena() {
  const engine = new ArenaEngine();
  engine.add('a', 'deagle'); engine.add('b', 'm4');
  Object.assign(engine.players.get('a'), { x: 100, y: 90, shieldUntil: 0 });
  Object.assign(engine.players.get('b'), { x: 300, y: 90, shieldUntil: 0 });
  return engine;
}
const engine = arena();
const a = engine.players.get('a'), b = engine.players.get('b');
engine.step(0.02, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(b.hp, 50, 'Desert Eagle first hit does 50 damage');
for (let i = 0; i < 30; i++) engine.step(0.02, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(b.hp, 50, 'Holding the mouse does not autofire a semiautomatic weapon');
engine.step(0.02, new Map([['a', { ...idle, trigger: 2 }]]));
assert.equal(b.hp, 0, 'Second hit kills even if mouse release arrives before the tick');
assert.equal(a.kills, 1); assert.equal(b.deaths, 1);
engine.step(3.01, new Map());
assert.equal(b.hp, 100, 'Dead players respawn');
assert.ok(b.shieldUntil > engine.time, 'Respawns have temporary protection');
const walls = arena();
Object.assign(walls.players.get('a'), { x: 200, y: 130, angle: Math.PI / 2 });
Object.assign(walls.players.get('b'), { x: 200, y: 300 });
walls.shoot(walls.players.get('a'));
assert.equal(walls.players.get('b').hp, 100, 'Container blocks bullets');
for (let i = 0; i < 100; i++) walls.step(0.03, new Map([['a', { ...idle, y: 1 }]]));
assert.ok(walls.players.get('a').y <= 144, 'Players cannot walk through containers');
assert.ok(!blocked(walls.players.get('a').x, walls.players.get('a').y));
const reload = arena();
reload.players.get('a').ammo = 2;
reload.step(0.01, new Map([['a', { ...idle, reload: true }]]));
reload.step(0.5, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(reload.players.get('b').hp, 100, 'Cannot shoot while reloading');
reload.step(2, new Map()); assert.equal(reload.players.get('a').ammo, WEAPONS.deagle.magazine);
const shotgun = arena();
Object.assign(shotgun.players.get('a'), { weapon: 'm870' });
Object.assign(shotgun.players.get('b'), { x: 160 });
shotgun.shoot(shotgun.players.get('a'));
assert.equal(shotgun.players.get('b').hp, 0, 'Shotgun pellets combine at close range');
const winner = arena();
winner.players.get('a').kills = 19; winner.players.get('b').hp = 50;
winner.shoot(winner.players.get('a')); assert.equal(winner.winner, 'a');
winner.step(8.1, new Map()); assert.equal(winner.winner, null); assert.equal(winner.players.get('a').kills, 0);
assert.equal(validInput({ ...idle, x: Infinity }), false);
assert.equal(validInput({ ...idle, x: 3 }), false);
assert.equal(validInput({ ...idle, trigger: -1 }), false);
console.log('Arena checks passed: two-hit kill, semiauto, walls, movement, reload, shotgun, respawn, round reset, invalid input.');
