import assert from 'node:assert/strict';
import { ArenaEngine, WEAPONS, blocked, validInput, weaponSpread, AIM_SPEED } from '../src/arena-engine.js';
import { createLatestSender } from '../src/arena-network.js';
import { assignSeats, validRules, firstStarter } from '../src/arena-lobby.js';
import { cameraPose, aimOnGround, relativeMove, wrapAngle } from '../src/arena-camera.js';

const idle = { x: 0, y: 0, angle: 0, fire: false, reload: false, trigger: 0 };
function arena() {
  const engine = new ArenaEngine();
  engine.add('a', 'deagle'); engine.add('b', 'm4');
  Object.assign(engine.players.get('a'), { x: 100, y: 90, shieldUntil: 0 });
  Object.assign(engine.players.get('b'), { x: 300, y: 90, shieldUntil: 0 });
  return engine;
}
const engine = arena();
const a = engine.players.get('a'), b = engine.players.get('b');
engine.step(0.02, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(b.hp, 50, 'Desert Eagle first hit does 50 damage');
for (let i = 0; i < 30; i++) engine.step(0.02, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(b.hp, 50, 'Holding the mouse does not autofire a semiautomatic weapon');
engine.step(0.02, new Map([['a', { ...idle, trigger: 2 }]]));
assert.equal(b.hp, 0, 'Second hit kills even if mouse release arrives before the tick');
assert.equal(a.kills, 1); assert.equal(b.deaths, 1);
engine.step(3.01, new Map());
assert.equal(b.hp, 100, 'Dead players respawn');
assert.ok(b.shieldUntil > engine.time, 'Respawns have temporary protection');
const walls = arena();
Object.assign(walls.players.get('a'), { x: 200, y: 130, angle: Math.PI / 2 });
Object.assign(walls.players.get('b'), { x: 200, y: 300 });
walls.shoot(walls.players.get('a'));
assert.equal(walls.players.get('b').hp, 100, 'Container blocks bullets');
for (let i = 0; i < 100; i++) walls.step(0.03, new Map([['a', { ...idle, y: 1 }]]));
assert.ok(walls.players.get('a').y <= 144, 'Players cannot walk through containers');
assert.ok(!blocked(walls.players.get('a').x, walls.players.get('a').y));
const reload = arena();
reload.players.get('a').ammo = 2;
reload.step(0.01, new Map([['a', { ...idle, reload: true }]]));
reload.step(0.5, new Map([['a', { ...idle, fire: true, trigger: 1 }]]));
assert.equal(reload.players.get('b').hp, 100, 'Cannot shoot while reloading');
reload.step(2, new Map()); assert.equal(reload.players.get('a').ammo, WEAPONS.deagle.magazine);
const shotgun = arena();
Object.assign(shotgun.players.get('a'), { weapon: 'm870' });
Object.assign(shotgun.players.get('b'), { x: 160 });
shotgun.shoot(shotgun.players.get('a'));
assert.equal(shotgun.players.get('b').hp, 0, 'Shotgun pellets combine at close range');
const winner = arena();
winner.players.get('a').kills = 19; winner.players.get('b').hp = 50;
winner.shoot(winner.players.get('a')); assert.equal(winner.winner, 'a');
winner.step(8.1, new Map()); assert.equal(winner.winner, null); assert.equal(winner.players.get('a').kills, 0);
assert.equal(validInput({ ...idle, x: Infinity }), false);
assert.equal(validInput({ ...idle, x: 3 }), false);
assert.equal(validInput({ ...idle, trigger: -1 }), false);
console.log('Arena checks passed: two-hit kill, semiauto, walls, movement, reload, shotgun, respawn, round reset, invalid input.');

for (const size of [1, 2, 3, 4, 5, 6]) {
  const members = new Map(Array.from({ length: size * 2 + 2 }, (_, i) => [`p${String(i).padStart(2, '0')}`, { team: 'auto' }]));
  let seats = assignSeats(members, new Map(), size);
  assert.equal(seats.size, size * 2, 'Seats never exceed the selected n vs n capacity');
  for (const side of ['red', 'blue']) assert.equal([...seats.values()].filter(t => t === side).length, size);
  const incumbent = [...seats.keys()][0];
  const incumbentSide = seats.get(incumbent);
  members.set('first', { team: incumbentSide });
  seats = assignSeats(members, seats, size);
  assert.equal(seats.get(incumbent), incumbentSide, 'New requests do not displace accepted players');
  assert.equal(seats.has('first'), false, 'A full team rejects another request');
  members.delete(incumbent);
  seats = assignSeats(members, seats, size);
  assert.equal(seats.size, size * 2, 'An empty seat can be filled');
  const match = new ArenaEngine({ mode: 'teams', size });
  for (const side of ['red', 'blue']) for (let i = 0; i < size; i++) match.add(`${side}${i}`, 'deagle', side);
  assert.equal(match.waiting, false);
  match.add('overflow', 'm4', 'red'); assert.equal(match.players.has('overflow'), false);
  assert.ok(match.players.get('red0').x < 200 && match.players.get('blue0').x > 1000, 'Teams spawn on opposite sides');
  match.remove('blue0'); assert.equal(match.waiting, true);
  const before = { ...match.players.get('red0') };
  match.step(0.05, new Map([['red0', { ...idle, x: 1, fire: true, trigger: 1 }]]));
  assert.equal(match.players.get('red0').x, before.x); assert.equal(match.players.get('red0').ammo, before.ammo);
  match.add('blue0', 'm4', 'blue'); assert.equal(match.waiting, false);
}
const teams = new ArenaEngine({ mode: 'teams', size: 2 });
teams.add('red1', 'deagle', 'red'); teams.add('red2', 'deagle', 'red'); teams.add('blue1', 'm4', 'blue'); teams.add('blue2', 'm4', 'blue');
Object.assign(teams.players.get('red1'), { x: 100, y: 90, angle: 0, shieldUntil: 0 });
Object.assign(teams.players.get('red2'), { x: 200, y: 90, shieldUntil: 0 });
Object.assign(teams.players.get('blue1'), { x: 300, y: 90, shieldUntil: 0 });
Object.assign(teams.players.get('blue2'), { x: 700, y: 690, shieldUntil: 0 });
teams.shoot(teams.players.get('red1'));
assert.equal(teams.players.get('red2').hp, 100, 'Friendly fire is disabled');
assert.equal(teams.players.get('blue1').hp, 50, 'Enemy receives Desert Eagle damage');
teams.teamScores.red = 19;
teams.shoot(teams.players.get('red1'));
assert.equal(teams.winner, 'red'); assert.equal(teams.teamScores.red, 20);
assert.equal(teams.players.get('red1').kills, 1, 'Victory uses team score, not individual score');
teams.step(8.1, new Map()); assert.equal(teams.winner, null); assert.deepEqual(teams.teamScores, { red: 0, blue: 0 });
assert.equal(validRules({ mode: 'teams', size: 2 }, false), false, 'IP rooms cannot enable teams');
assert.equal(validRules({ mode: 'teams', size: 7 }, true), false);
assert.equal(validRules({ mode: 'teams', size: 1.5 }, true), false);
console.log('Team checks passed: 1–6 vs 1–6, capacity, seat races, spawn sides, readiness, friendly fire, team victory, round reset, IP restrictions.');

const starters = new Map([['zzz', { order: 1, startedAt: 1000 }], ['aaa', { order: 2, startedAt: 500 }]]);
assert.equal(firstStarter(starters), 'zzz', 'The first starter owns the game even if a later peer ID or clock sorts earlier');
starters.delete('zzz'); assert.equal(firstStarter(starters), 'aaa');
starters.set('zzz', { order: 3, startedAt: 1500 }); assert.equal(firstStarter(starters), 'aaa', 'Returning creator cannot take back ownership');
assert.equal(validRules({ mode: 'ffa', size: 1, view: 'fps' }, false), true);
assert.equal(validRules({ mode: 'ffa', size: 1, view: 'invalid' }, true), false);
const pose = cameraPose({ x: 600, y: 380 }, 'top', 0, 0);
const center = aimOnGround(pose, 0, 0, 75, 1.6);
assert.ok(Math.abs(center.x - 600) < 0.001);
const narrow = aimOnGround(pose, 0.5, 0, 55, 1.6), wide = aimOnGround(pose, 0.5, 0, 110, 1.6);
assert.ok(wide.x > narrow.x, 'Larger FOV exposes more world space');
assert.ok(relativeMove(0, 1, Math.PI / 2).y > 0.99, 'FPS forward follows camera yaw');
assert.ok(relativeMove(1, 0, 0).y > 0.99, 'FPS strafe is camera relative');
assert.ok(Math.abs(wrapAngle(100)) <= Math.PI);
const pitched = arena();
pitched.players.get('a').pitch = 0.6;
pitched.shoot(pitched.players.get('a'));
assert.equal(pitched.players.get('b').hp, 100, 'Aiming above an enemy does not hit their body');
pitched.players.get('a').pitch = -0.6;
pitched.shoot(pitched.players.get('a'));
assert.equal(pitched.players.get('b').hp, 100, 'Aiming at the floor does not hit an enemy behind the impact');
assert.ok(pitched.traces.every(t => t.endZ >= 0));
assert.equal(validInput({ ...idle, pitch: 2 }), false);
console.log('Camera checks passed: first-starter authority, succession, FOV, movement transforms, vertical hit detection, view validation.');

const aimed = arena(), hip = arena();
aimed.step(0.05, new Map([['a', { ...idle, x: 1, aiming: true }]]));
hip.step(0.05, new Map([['a', { ...idle, x: 1 }]]));
assert.ok(Math.abs((aimed.players.get('a').x - 100) / (hip.players.get('a').x - 100) - AIM_SPEED) < 0.00001);
assert.equal(aimed.players.get('a').aiming, true);
assert.ok(weaponSpread('m4', true) < weaponSpread('m4', false));
assert.ok(weaponSpread('m870', true) < weaponSpread('m870', false));
assert.equal(weaponSpread('deagle', true), 0);
aimed.players.get('a').ammo = 2;
aimed.step(0.01, new Map([['a', { ...idle, aiming: true, reload: true }]]));
assert.equal(aimed.players.get('a').aiming, false, 'Reload interrupts precision aim');
assert.equal(WEAPONS.deagle.damage, 50, 'Aim does not alter the two-hit damage model');
assert.equal(validInput({ ...idle, aiming: 'yes' }), false);
assert.equal('cooldown' in aimed.snapshot().players[0], false, 'Internal simulation fields are not sent');
const sent = [], releases = [];
const queue = createLatestSender((value, peer) => { sent.push([peer, value]); return new Promise(resolve => releases.push(resolve)); });
queue.send(1, ['slow']); queue.send(2, ['slow']); queue.send(3, ['slow']); queue.send(4, ['fast']);
assert.deepEqual(sent, [['slow', 1], ['fast', 4]], 'Slow recipients do not block other recipients');
releases[0](); await Promise.resolve();
assert.deepEqual(sent, [['slow', 1], ['fast', 4], ['slow', 3]], 'Only newest pending snapshot is transmitted');
queue.send(5, ['slow']); queue.remove('slow'); releases[2](); await Promise.resolve();
assert.equal(sent.length, 3, 'Leaving discards pending snapshots');
queue.close(); releases[1](); queue.send(6, ['fast']); await Promise.resolve(); assert.equal(sent.length, 3);
console.log('Aim/network checks passed: aim speed, tighter spread, reload, damage invariance, latest-only snapshots, per-peer backpressure, cleanup.');
